// generated by jsonenums -suffix= -type=SchoolType; DO NOT EDIT

package enums

import (
	"encoding/json"
	"fmt"
)

var (
	_SchoolTypeNameToValue = map[string]SchoolType{
		"PRIMARY_SCHOOL":   PrimarySchool,
		"SECONDARY_SCHOOL": SecondarySchool,
		"HIGH_SCHOOL":      HighSchool,
		"COLLEGE":          College,
		"OTHER":            OtherSchool,
	}

	_SchoolTypeValueToName = map[SchoolType]string{
		PrimarySchool:   "PRIMARY_SCHOOL",
		SecondarySchool: "SECONDARY_SCHOOL",
		HighSchool:      "HIGH_SCHOOL",
		College:         "COLLEGE",
		OtherSchool:     "OTHER",
	}
)

func init() {
	var v SchoolType
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_SchoolTypeNameToValue = map[string]SchoolType{
			interface{}(PrimarySchool).(fmt.Stringer).String():   PrimarySchool,
			interface{}(SecondarySchool).(fmt.Stringer).String(): SecondarySchool,
			interface{}(HighSchool).(fmt.Stringer).String():      HighSchool,
			interface{}(College).(fmt.Stringer).String():         College,
			interface{}(OtherSchool).(fmt.Stringer).String():     OtherSchool,
		}
	}
}

// MarshalJSON is generated so SchoolType satisfies json.Marshaler.
func (r SchoolType) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _SchoolTypeValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid SchoolType: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so SchoolType satisfies json.Unmarshaler.
func (r *SchoolType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SchoolType should be a string, got %s", data)
	}
	v, ok := _SchoolTypeNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid SchoolType %q", s)
	}
	*r = v
	return nil
}
